version: v1.0.0.{build}
os: Visual Studio 2017

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '1.0.0.{build}'
  assembly_file_version: '1.0.0.{build}'

artifacts:
- path: Emitter\**\*.nupkg

deploy:
  - provider: Environment
    name: Public S3
    artifact: /.*\.nupkg/
    on:
      branch: master

  - provider: NuGet
    api_key:
      secure: rU+w5deWOMiUmQES2u4bz1o0ElWYIfjxKVokp+QUjjidbGiRJwK6s1LcTNRrAde3
    artifact: /.*\.nupkg/   
    on:
      branch: master