version: v1.0.0.{build}
os: Visual Studio 2015

init:
  - ps: iex ((new-object net.webclient).DownloadString('https://gist.githubusercontent.com/PureKrome/0f79e25693d574807939/raw/8cf3160c9516ef1f4effc825c0a44acc918a0b5a/appveyor-build-info.ps'))
  
install:
  - ps: iex .\build\show-dotnet-info.ps1
  - ps: iex .\build\install-dotnet.ps1
  - "SET PATH=C:\\Program Files\\dotnet\\bin;%PATH%"

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '1.0.0.{build}'
  assembly_file_version: '1.0.0.{build}'

before_build:
- cmd: >-
    dotnet restore src\Emitter.Server && dotnet restore src\Emitter.Runtime && dotnet restore src\Emitter.Storage.S3

    cd build && npm install && node add-project-version.js && cd..

build_script:
- cmd: >-
    dotnet pack src\Emitter.Runtime --configuration Release --output "Emitter" && dotnet pack src\Emitter.Storage.S3 --configuration Release --output "Emitter" && dotnet pack src\Emitter.Server --configuration Release --output "Emitter"
test: off

artifacts:
- path: Emitter\**\*.nupkg

deploy:
  - provider: Environment
    name: Public S3
    artifact: /.*\.nupkg/
    on:
      branch: master

  - provider: NuGet
    api_key:
      secure: rU+w5deWOMiUmQES2u4bz1o0ElWYIfjxKVokp+QUjjidbGiRJwK6s1LcTNRrAde3
    artifact: /.*\.nupkg/   
    on:
      branch: master